version: "3.8"
services:

  bot:
    build: .
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8011:8011"
    command: python main.py
    env_file:
      - env/.env.local
    networks:
      - qr_network

networks:
  qr_network:
    external: true
