version: "3.8"
services:

  bot:
    build: .
    restart: always
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8011:8011"
    command: python main_prod.py
    env_file:
      - env/.env.prod
    networks:
      - qr_network

networks:
  qr_network:
    external: true
